# functional progrmming
    -lambda
    -map
    -filter
    all are anonymous functions
    we create here small functions
    

In [2]:
#lambda
#syntax:lambda argument:expression
#no.of argumnets,only single expression
def add(a,b):
    return a+b
add(3,4)

7

In [3]:
l=lambda x,y:x+y
print(l(2,3))

5


In [9]:
#map
#syntax:map(function,iterable1,iterable2....)
def mul(a):
    return a*a
x=3
l=map(mul,[1,2,3])

print(list(l))

[1, 4, 9]


In [15]:
#input:[ram,sita]
#o/p:[RAM,SITA]
l=['ram','sita']


In [14]:
def upper(i):
    return i.upper()
x=map(upper,l)
print(list(x))    

['RAM', 'SITA']


In [16]:
a=list(map(str.upper,l))
a

['RAM', 'SITA']

In [8]:
#map with lambda
l=[1,2,3,4]
y=list(map(lambda x:x**3,l))
print(y)

[1, 8, 27, 64]


In [9]:
l=[1,2,3,4]
l1=[5,6,7,8]
y=list(map(lambda a,b:a+b,l,l1))
print(y)

[6, 8, 10, 12]


In [13]:
#filter
y=list(filter(lambda x:x>5,range(1,10)))
print(y)

[6, 7, 8, 9]


# data science packages
 -numpy,pandas and malpotilib

# numpy
-math and random can use these are submodules of numpy
-used to create arrays(ganeral and random)

In [16]:
import numpy as np

In [17]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [18]:
#creating arrys using numpy
#array is submodule in numpy used to create arrays


In [21]:
ar=np.array("string is a data type".split())
print(ar)

['string' 'is' 'a' 'data' 'type']


In [22]:
#row matrix#create arrays by using tuple and list
a=np.array([1,1,1])
print(a)

[1 1 1]


In [23]:
b=np.array((1,1,1))
print(b)

[1 1 1]


In [24]:
t=np.array([[1],[2],[3]])
print(t)

[[1]
 [2]
 [3]]


In [26]:
li=np.array([(1,2),(3,4),("rutu","geetha")])#column matrix
print(li)

[['1' '2']
 ['3' '4']
 ['rutu' 'geetha']]


In [32]:
#creatin array using range method
x=np.array(range(1,10,2))
x

array([1, 3, 5, 7, 9])

In [37]:
#creating array using arange() method
#range-python
#arange()-numpy
#arange(lw,up,step)-inclusive
import numpy as np

In [41]:
y=np.arange(1,10)#upper boundary exclusive
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

In [42]:
#creating arrayswith arange().reshape()
#row matrix 2d array using reshape()
#based on size of array
#np.arange(30).reshape(1,30)#row matrix
#(5,6),(2,15),(30,1)#column matrix

In [45]:
import numpy as np


In [47]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
arr1=np.arange(30).reshape(6,-1)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [51]:
arr2=np.arange(40,60).reshape(4,5)
arr2

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [53]:
#random
#random.randit(,)
#random.randint(,,)
#random.randint(,())
'''random.random(())
random.rand(,)
random.randn(,)'''


In [64]:
r=np.random.randint(10)
print(r)#from 0 to 10
r1=np.random.randint(10,40)
print(r1)#from 10 to 40
r2=np.random.randint(10,50,6)#generates 6 values in this range
print(r2)#row matrix
r3=np.random.randint(10,100,(2,4))#generates random array of size(2,4)
print(r3)
r4=np.random.randint(10,50,12).reshape(4,3)#reshaping the random 
print(r4)


9
24
[12 26 44 11 23 12]
[[61 65 10 89]
 [65 86 40 20]]
[[42 38 48]
 [20 16 19]
 [27 14 16]
 [49 46 23]]


In [105]:
rn=np.random.random((2,4))
rn#random values between 0 and 1 of size 2,4


array([[0.12134653, 0.24670893, 0.45512985, 0.65678713],
       [0.72191989, 0.37574559, 0.33206653, 0.11268555]])

In [108]:
rd=np.random.rand(3,2) #between 0 and 1
rd#generates standard deviation values randomly

array([[0.5481271 , 0.91351152],
       [0.98787765, 0.31345217],
       [0.62859671, 0.99984396]])

In [109]:
rdn=np.random.randn(3,2)#from -1 to 1
rdn

array([[-0.570262  ,  0.32393833],
       [ 0.56991104, -1.78763553],
       [ 1.22227082, -0.28498452]])

In [69]:
#using linspace
print(np.linspace(10,20,6))#partitioning the range with 3 rd argument
print(np.linspace(3,9,4))#both limitds are inclusive

[10. 12. 14. 16. 18. 20.]
[3. 5. 7. 9.]


In [70]:
#creating the array with 0's ,1's and full
o=np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
f=np.full((2,3),"clg")
f

array([['clg', 'clg', 'clg'],
       ['clg', 'clg', 'clg']], dtype='<U3')

In [82]:
f=np.full((3,2),5)
print(f)
f.fill(9)#it will accept only floating values
f

[[5 5]
 [5 5]
 [5 5]]


array([[9, 9],
       [9, 9],
       [9, 9]])

In [84]:
st=np.array([["hi","hello"],[12,34],[3.4,5.6]])
print(st)
type(st)
st.dtype#numpy attributes

[['hi' 'hello']
 ['12' '34']
 ['3.4' '5.6']]


dtype('<U5')

In [80]:
np.diag(st)

array(['hi', '34'], dtype='<U5')

In [81]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
print(np.diag([1,2,3,4]))#creates diagonal matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [86]:
#slicing
#accesing one particular element
#ar[:] lw,up
#ar[row:col]
#ar[row][index]

In [89]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [90]:
#index:0 to len(iterable)-1
arr1[2:5]#3rd to 5 th

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr1[::]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [93]:
arr1[2][2]

12

In [95]:
arr1[3:5,1:4]

array([[16, 17, 18],
       [21, 22, 23]])

In [96]:
arr1[3][1]

16

In [98]:
r5=np.random.randint(10,40,(4,4))
print(r5)

[[24 11 25 20]
 [31 12 10 19]
 [28 34 23 20]
 [30 24 28 30]]


In [99]:
r5[2:]

array([[28, 34, 23, 20],
       [30, 24, 28, 30]])

In [100]:
r5[2:,:3]

array([[28, 34, 23],
       [30, 24, 28]])

In [101]:
r5>40#fancy matrix

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [102]:
r5[:]

array([[24, 11, 25, 20],
       [31, 12, 10, 19],
       [28, 34, 23, 20],
       [30, 24, 28, 30]])

In [110]:
ar=np.arange(25).reshape(5,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
m=np.random.randint(30,60,(5,5))
m

array([[56, 41, 53, 41, 49],
       [30, 40, 38, 36, 34],
       [57, 49, 51, 30, 52],
       [40, 47, 37, 41, 57],
       [52, 48, 57, 42, 59]])

In [113]:
print(ar-m)
print(m-ar)
print(ar*m)
print(m/ar)
print(np.min(m))
print(np.max(ar))

[[-56 -40 -51 -38 -45]
 [-25 -34 -31 -28 -25]
 [-47 -38 -39 -17 -38]
 [-25 -31 -20 -23 -38]
 [-32 -27 -35 -19 -35]]
[[56 40 51 38 45]
 [25 34 31 28 25]
 [47 38 39 17 38]
 [25 31 20 23 38]
 [32 27 35 19 35]]
[[   0   41  106  123  196]
 [ 150  240  266  288  306]
 [ 570  539  612  390  728]
 [ 600  752  629  738 1083]
 [1040 1008 1254  966 1416]]
[[        inf 41.         26.5        13.66666667 12.25      ]
 [ 6.          6.66666667  5.42857143  4.5         3.77777778]
 [ 5.7         4.45454545  4.25        2.30769231  3.71428571]
 [ 2.66666667  2.9375      2.17647059  2.27777778  3.        ]
 [ 2.6         2.28571429  2.59090909  1.82608696  2.45833333]]
30
24


<ipython-input-113-29334e287ab9>:4: RuntimeWarning: divide by zero encountered in true_divide
  print(m/ar)


In [115]:
#scientific computation
print(np.mean(m))
print(np.std(m))
print(np.median(ar))
print(ar.dot(m))#multiplies both matrices

45.48
8.6214615930247
12.0
[[ 472  471  479  387  545]
 [1647 1596 1659 1337 1800]
 [2822 2721 2839 2287 3055]
 [3997 3846 4019 3237 4310]
 [5172 4971 5199 4187 5565]]


In [116]:
#broad casting
#huge conversion and applying a single variable
print(ar+5)
print(ar+4)
print(ar/3)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]
 [19 20 21 22 23]
 [24 25 26 27 28]]
[[0.         0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667 3.        ]
 [3.33333333 3.66666667 4.         4.33333333 4.66666667]
 [5.         5.33333333 5.66666667 6.         6.33333333]
 [6.66666667 7.         7.33333333 7.66666667 8.        ]]


In [117]:
#logarithms and exponentials
#np.log(ele)
#np.log(exp)
np.log(0)

<ipython-input-117-67a9467c7962>:2: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [118]:
np.log(2)

0.6931471805599453

In [119]:
np.log2(2)

1.0

In [120]:
np.log([2,3,4])

array([0.69314718, 1.09861229, 1.38629436])

In [122]:
np.log(1)

0.0

In [124]:
np.exp(1)

2.718281828459045

In [125]:
dir(np.log)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

In [126]:
np.exp(2)-1

6.38905609893065

In [127]:
def greater(m,n):
    if m>n:
        print(m)
    else:
        print(n)
greater(2,3)

3


In [128]:
greater([1,2,3],[4,5,6])

[4, 5, 6]


In [131]:
v=np.vectorize(greater)
print(np.vectorize(greater))

In [132]:
help(np.vectorize)

Help on class vectorize in module numpy:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The 

# pandas
 - means panel data
 -one of the data science packages
 -used for data manipulation and analysis,cleaning
 -contains mainly two data structures in it
      1.series
      2.data frames
 -sequence of data
 -data frames is a data with rows and columns
  

In [134]:
##installation
#-- pip install pandas

In [135]:
import pandas

In [139]:
import pandas as pd

In [137]:
pd.__version__

'1.1.3'

### series
 - syntax:pd.Series(data,index,dtype)

In [142]:
import pandas as pd
s='hello'
pd.Series(s)

0    hello
dtype: object

In [143]:
s1="hi hello good morning".split()

pd.Series(s1)

0         hi
1      hello
2       good
3    morning
dtype: object

In [144]:
pd.Series(s1,index=[1,2,3,4])

1         hi
2      hello
3       good
4    morning
dtype: object

In [147]:
l=[12,'name',3.4]
pd.Series(l,index=('int','string','float'))

int         12
string    name
float      3.4
dtype: object

In [150]:
t=('a','e','i','o','u')
pd.Series(t,index=['v1','v2','v3','v4','v5'])


v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [163]:
d={1:"hi",2:3,3.5:4.5}
pd.Series(d)

1.0     hi
2.0      3
3.5    4.5
dtype: object

# Data Frames

In [166]:
st="clear mam not understand".split()
pd.DataFrame(st)

0
0       clear
1         mam
2         not
3  understand

In [170]:
l1=[[1,2,3],[6,7,8]]
pd.DataFrame(l1,index=['list1','list2'])

0  1  2
list1  1  2  3
list2  6  7  8

In [179]:
d={1:'hi',3:'hlo',4:5.7,5:"vignan"}
pd.DataFrame(d,index=['dict1','dict2',2,3])

1    3    4       5
dict1  hi  hlo  5.7  vignan
dict2  hi  hlo  5.7  vignan
2      hi  hlo  5.7  vignan
3      hi  hlo  5.7  vignan

In [180]:
dic={'names':['vasu','mahi','mouni'],'marks':[23,32,43],'id':[2,3,4]}
pd.DataFrame(dic,index=['stu1','stu2','stu3'])

names  marks  id
stu1   vasu     23   2
stu2   mahi     32   3
stu3  mouni     43   4

In [181]:
d={"key1":('a','y','r'),"key2":(4,5,6)}
pd.DataFrame(d,index=[1,2,3])

key1  key2
1    a     4
2    y     5
3    r     6

In [182]:
import numpy as np

In [194]:
s=pd.Series(np.random.randint(20,40,8))
print(s)

0    26
1    34
2    36
3    31
4    32
5    37
6    23
7    22
dtype: int32


In [197]:
s[3:]

3    31
4    32
5    37
6    23
7    22
dtype: int32

In [198]:
s[5:7]

5    37
6    23
dtype: int32

In [199]:
s[1:6:2]

1    34
3    31
5    37
dtype: int32

# Data Analysis and Manipulation


In [202]:
df1=pd.DataFrame({'month':[2,3,4,5],'days':[23,45,67,89]},index=[2001,2002,2003,3004])    
df1

month  days
2001      2    23
2002      3    45
2003      4    67
3004      5    89

In [206]:
df2=pd.DataFrame({'n_p':[2,3,4,5],'n_h':[23,45,67,89]},index=[2009,2002,2003,3004])  
df2

n_p  n_h
2009    2   23
2002    3   45
2003    4   67
3004    5   89

In [207]:
df1.join(df2)

month  days  n_p   n_h
2001      2    23  NaN   NaN
2002      3    45  3.0  45.0
2003      4    67  4.0  67.0
3004      5    89  5.0  89.0

In [208]:
df2.join(df1)

n_p  n_h  month  days
2009    2   23    NaN   NaN
2002    3   45    3.0  45.0
2003    4   67    4.0  67.0
3004    5   89    5.0  89.0

In [223]:
df3=pd.DataFrame({'b':[23,35,47,59],'n':[12,5,7,9]},index=[2012,2002,2003,3004])  
df3

b   n
2012  23  12
2002  35   5
2003  47   7
3004  59   9

In [215]:
df4=pd.DataFrame({'b':[23,35,47,59],'n':[3,5,7,9]},index=[2012,2002,2003,3004]) 
df4

b  n
2012  23  3
2002  35  5
2003  47  7
3004  59  9

In [216]:
df3.join(df4)

a  n_h     b    n
2009  23    3   NaN  NaN
2002  35    5  35.0  5.0
2003  47    7  47.0  7.0
3004  59    9  59.0  9.0

In [219]:
df3.merge(df4)

b  n
0  23  3
1  35  5
2  47  7
3  59  9

In [224]:
df4.merge(df3)

b  n
0  35  5
1  47  7
2  59  9

In [226]:
pd.concat([df3,df4])

b   n
2012  23  12
2002  35   5
2003  47   7
3004  59   9
2012  23   3
2002  35   5
2003  47   7
3004  59   9

In [229]:
dates=pd.date_range('2020-10-20','2020-10-25')
pd.Series(dates,index=['day1','day2','day6','day4','day5','day6'])


day1   2020-10-20
day2   2020-10-21
day6   2020-10-22
day4   2020-10-23
day5   2020-10-24
day6   2020-10-25
dtype: datetime64[ns]

In [231]:
marks_df=pd.read_csv('marks.csv')
marks_df

name  maths  science  engish
0    a     23     34.0    56.0
1    b     23      4.0     5.0
2    c     34     56.0    89.0
3    d     23     54.0    67.0
4    e     23      4.0     5.0
5    f      3      5.0     6.0
6    g     56     67.0    89.0
7    h    567      5.0    78.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN

In [232]:
marks_df.head()

name  maths  science  engish
0    a     23     34.0    56.0
1    b     23      4.0     5.0
2    c     34     56.0    89.0
3    d     23     54.0    67.0
4    e     23      4.0     5.0

In [233]:
marks_df.tail()

name  maths  science  engish
5    f      3      5.0     6.0
6    g     56     67.0    89.0
7    h    567      5.0    78.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN

In [234]:
marks_df.head(3)

name  maths  science  engish
0    a     23     34.0    56.0
1    b     23      4.0     5.0
2    c     34     56.0    89.0

In [235]:
marks_df.tail(4)

name  maths  science  engish
6    g     56     67.0    89.0
7    h    567      5.0    78.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN

In [238]:
pd.read_csv('marks.csv',header=None)

0      1        2       3
0   name  maths  science  engish
1      a     23       34      56
2      b     23        4       5
3      c     34       56      89
4      d     23       54      67
5      e     23        4       5
6      f      3        5       6
7      g     56       67      89
8      h    567        5      78
9      i      4        4     NaN
10     j      5      NaN     NaN

In [239]:
pd.read_csv('marks.csv',usecols=['name','maths'])

name  maths
0    a     23
1    b     23
2    c     34
3    d     23
4    e     23
5    f      3
6    g     56
7    h    567
8    i      4
9    j      5

In [243]:
df=pd.read_csv('marks.csv',names=['n','b','v','t'])
df

n      b        v       t
0   name  maths  science  engish
1      a     23       34      56
2      b     23        4       5
3      c     34       56      89
4      d     23       54      67
5      e     23        4       5
6      f      3        5       6
7      g     56       67      89
8      h    567        5      78
9      i      4        4     NaN
10     j      5      NaN     NaN

In [244]:
df['n']

0     name
1        a
2        b
3        c
4        d
5        e
6        f
7        g
8        h
9        i
10       j
Name: n, dtype: object

In [242]:
marks_df.columns

Index(['name', 'maths', 'science', 'engish'], dtype='object')

In [247]:
df[['n','b']]

n      b
0   name  maths
1      a     23
2      b     23
3      c     34
4      d     23
5      e     23
6      f      3
7      g     56
8      h    567
9      i      4
10     j      5

In [248]:
marks_df.info

<bound method DataFrame.info of   name  maths  science  engish
0    a     23     34.0    56.0
1    b     23      4.0     5.0
2    c     34     56.0    89.0
3    d     23     54.0    67.0
4    e     23      4.0     5.0
5    f      3      5.0     6.0
6    g     56     67.0    89.0
7    h    567      5.0    78.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN>

In [249]:
marks_df.describe()#statistics of data

maths    science     engish
count   10.000000   9.000000   8.000000
mean    76.100000  25.888889  49.375000
std    173.216275  26.839544  38.048606
min      3.000000   4.000000   5.000000
25%      9.500000   4.000000   5.750000
50%     23.000000   5.000000  61.500000
75%     31.250000  54.000000  80.750000
max    567.000000  67.000000  89.000000

In [251]:
marks_df.dtypes

name        object
maths        int64
science    float64
engish     float64
dtype: object

In [252]:
marks_df

name  maths  science  engish
0    a     23     34.0    56.0
1    b     23      4.0     5.0
2    c     34     56.0    89.0
3    d     23     54.0    67.0
4    e     23      4.0     5.0
5    f      3      5.0     6.0
6    g     56     67.0    89.0
7    h    567      5.0    78.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN

In [253]:
marks_df.shape

(10, 4)

In [255]:
marks_df.index

RangeIndex(start=0, stop=10, step=1)

In [258]:
marks_df.shape[0]

10

In [259]:
marks_df.sort_values('maths')

name  maths  science  engish
5    f      3      5.0     6.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN
0    a     23     34.0    56.0
1    b     23      4.0     5.0
3    d     23     54.0    67.0
4    e     23      4.0     5.0
2    c     34     56.0    89.0
6    g     56     67.0    89.0
7    h    567      5.0    78.0

In [260]:
marks_df.sort_values('engish',ascending=False)

name  maths  science  engish
2    c     34     56.0    89.0
6    g     56     67.0    89.0
7    h    567      5.0    78.0
3    d     23     54.0    67.0
0    a     23     34.0    56.0
5    f      3      5.0     6.0
1    b     23      4.0     5.0
4    e     23      4.0     5.0
8    i      4      4.0     NaN
9    j      5      NaN     NaN

In [263]:
marks_df['college']='abc'

In [264]:
marks_df.sample(5)

name  maths  science  engish college
7    h    567      5.0    78.0     abc
1    b     23      4.0     5.0     abc
8    i      4      4.0     NaN     abc
2    c     34     56.0    89.0     abc
9    j      5      NaN     NaN     abc

In [266]:
marks_df.maths.value_counts()

23     4
56     1
567    1
5      1
4      1
3      1
34     1
Name: maths, dtype: int64

In [267]:
marks_df.isnull()

name  maths  science  engish  college
0  False  False    False   False    False
1  False  False    False   False    False
2  False  False    False   False    False
3  False  False    False   False    False
4  False  False    False   False    False
5  False  False    False   False    False
6  False  False    False   False    False
7  False  False    False   False    False
8  False  False    False    True    False
9  False  False     True    True    False

In [268]:
marks_df.isna()

name  maths  science  engish  college
0  False  False    False   False    False
1  False  False    False   False    False
2  False  False    False   False    False
3  False  False    False   False    False
4  False  False    False   False    False
5  False  False    False   False    False
6  False  False    False   False    False
7  False  False    False   False    False
8  False  False    False    True    False
9  False  False     True    True    False

In [270]:
marks_df.dropna()

name  maths  science  engish college
0    a     23     34.0    56.0     abc
1    b     23      4.0     5.0     abc
2    c     34     56.0    89.0     abc
3    d     23     54.0    67.0     abc
4    e     23      4.0     5.0     abc
5    f      3      5.0     6.0     abc
6    g     56     67.0    89.0     abc
7    h    567      5.0    78.0     abc